"""adding autiting table

Revision ID: 45b15deacf99
Revises: b2639490c6dd
Create Date: 2021-01-01 11:07:06.998803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b15deacf99'
down_revision = 'b2639490c6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
